---
name: "Docker: Cleanup Images"

on:
  pull_request:
    types: ["closed"]
  push:
    paths: [".github/workflows/docker-cleanup-pr-images.yaml"]

concurrency:
  group: registry-tags-cleanup
  cancel-in-progress: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm@sha256:aedf26ccde02f734a8d8879778f5daac6c71609bb1df1b5a3e9d708f3c2827a2
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Install dependencies
        run: npm install

      - name: Generate matrix
        run: npm run genmatrix
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}

      - name: Save Matrix
        id: matrix
        run: |
          matrix=$(cat matrix.json)
          echo "matrix=${matrix}" | tee $GITHUB_OUTPUT

  cleanup-tagged-images:
    name: "${{ matrix.job_name }}"
    runs-on: ubuntu-latest
    needs: generate-matrix
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix)['include'].length > 0 }}
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Clean PR Images
        uses: stumpylog/image-cleaner-action/ephemeral@0924047a3709a8f39313ec9e5f5888597e3bf81b # v0.8.0
        with:
          owner: "${{ github.repository_owner }}"
          repo_name: "${{ github.repository }}"
          token: "${{ secrets.GHCR_RW_TOKEN }}"
          package_name: "${{ matrix.job_name }}"
          is_org: "true"
          do_delete: "true"
          scheme: "pull_request"
          match_regex: '^pr-(\d+)$|^(\d+)$'

  cleanup-untagged-images:
    name: "${{ matrix.job_name }}"
    runs-on: ubuntu-latest
    needs:
      - generate-matrix
      - cleanup-tagged-images
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix)['include'].length > 0 }}
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Clean untagged images
        uses: stumpylog/image-cleaner-action/untagged@0924047a3709a8f39313ec9e5f5888597e3bf81b # v0.8.0
        with:
          owner: "${{ github.repository_owner }}"
          token: "${{ secrets.GHCR_RW_TOKEN }}"
          package_name: "${{ matrix.job_name }}"
          do_delete: "true"
          is_org: "true"
