---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docker: Build and Push"

on:
  push:
    branches: ["main"]
    paths: ["containers/**"]
  pull_request:
    paths: ["containers/**"]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm@sha256:aedf26ccde02f734a8d8879778f5daac6c71609bb1df1b5a3e9d708f3c2827a2
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Install dependencies
        run: npm install

      - name: Generate matrix
        run: npm run genmatrix
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}

      - name: Save Matrix
        id: matrix
        run: |
          matrix=$(cat matrix.json)
          echo "matrix=${matrix}" | tee "$GITHUB_OUTPUT"

  build:
    name: ${{ matrix.job_name }}
    needs: generate-matrix
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-docker-build-push.yaml@f4dce998a168bbe2e53664acf4dd29407cd3d29f # v3.4.19
    # if: ${{ fromJson(needs.generate-matrix.outputs.matrix)['include'].length > 0 }}
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    secrets: inherit
    with:
      image: ${{ matrix.image_name }}
      platforms: linux/amd64, linux/arm64
      tags: ${{ matrix.version }}
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      dry-run: false
