---
name: "Docker: Cleanup Images"

on:
  pull_request:
    types: ["closed"]
  push:
    paths: [".github/workflows/docker-cleanup-pr-images.yaml"]

concurrency:
  group: registry-tags-cleanup
  cancel-in-progress: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Install dependencies
        run: npm install

      - name: Generate matrix
        id: generate-matrix
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          matrix=$(node .github/scripts/generate_matrix.mjs)
          echo "matrix=${matrix}" | tee $GITHUB_OUTPUT

  cleanup-tagged-images:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      TOKEN: ${{ secrets.GHCR_RW_TOKEN }}
    steps:
      - name: Clean PR Images
        if: "${{ env.TOKEN != '' }}"
        uses: stumpylog/image-cleaner-action/ephemeral@v0.8.0
        with:
          token: "${{ env.TOKEN }}"
          owner: "${{ github.repository_owner }}"
          is_org: "true"
          do_delete: "true"
          package_name: "${{ matrix.image_name }}"
          scheme: "pull_request"
          repo_name: "${{ github.repository }}"
          match_regex: '^pr-(\d+)$|^(\d+)$'

  cleanup-untagged-images:
    runs-on: ubuntu-latest
    needs:
      - generate-matrix
      - cleanup-images
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      TOKEN: ${{ secrets.GHCR_RW_TOKEN }}
    steps:
      - name: Clean untagged images
        if: "${{ env.TOKEN != '' }}"
        uses: stumpylog/image-cleaner-action/untagged@v0.8.0
        with:
          token: "${{ env.TOKEN }}"
          owner: "${{ github.repository_owner }}"
          do_delete: "true"
          is_org: "true"
          package_name: "${{ matrix.image_name }}"
