---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Meta: Add all issues to project"

on:
  issues:
    types: ["opened"]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issue.title, 'Renovate Dashboard') && !contains(github.event.issue.title, 'Link Checker Dashboard') }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/mirceanton/projects/1
          github-token: ${{ steps.app-token.outputs.token }}
